### ISSUE TITLE
[ARM64EC] Steam on Wine has random crash in steamwebhelper

### ISSUE THREAD

**Issue by Art-Chen** [FEX-Emu/FEX#4493]
**FEX Version:** git head: 09e622d5a03d55e39ff81668ab08a6595ddc5c5b
**Wine Version**: Wine tag 10.5

### Log

`097c:warn:seh:dispatch_exception "src\\common\\asyncfileiohandler.cpp (769) : dwRet != WAIT_FAILED\n"
097c:trace:seh:dispatch_exception code=40010006 (DBG_PRINTEXCEPTION_C) flags=0 addr=000000007A322339
097c:trace:seh:dispatch_exception  info[0]=0000000000000040
097c:trace:seh:dispatch_exception  info[1]=000000000FF9E900
097c:trace:seh:dispatch_exception  pc=0000007fff89b5c8  sp=0000000115ffee30  lr=0000000000000000  fp=000000007ac77000
097c:trace:seh:dispatch_exception  x0=0000000000000000  x1=000000000ff9e428  x2=0000000000000001  x3=00000001038bba90
097c:trace:seh:dispatch_exception  x4=0000000115fff160  x5=0000000000000000  x6=000000000ece2000  x7=000000007a851cec
097c:trace:seh:dispatch_exception  x8=0000000000000090  x9=0000000000005d17 x10=00000000000001e0 x11=0000000100210000
097c:trace:seh:dispatch_exception x12=00000000000000b0 x13=00000000000011d1 x14=000000000ff9e404 x15=000000000ff9e418
097c:trace:seh:dispatch_exception x16=0000007fffa13210 x17=0000000115fff1f0 x18=000000000ece0000 x19=000000000ff9e700
097c:trace:seh:dispatch_exception x20=000000000ff9e428 x21=0000000000000001 x22=00000001038ce3e0 x23=0000000115fffd20
097c:trace:seh:dispatch_exception x24=0000000000000001 x25=000000007ac78000 x26=0000000000000246 x27=000000007ac78002
097c:trace:seh:dispatch_exception x28=0000000115fff2d0 cpsr=20000000 fpcr=00000000 fpsr=00000000
097c:trace:seh:call_seh_handlers calling handler 0000007FFF89B5E0 (rec=0000000115FFED70, frame=115fff1f0 context=0000000115FFE9C0, dispatch=0000000115FFE5F8)
097c:trace:seh:RtlUnwindEx code=40010006 flags=2 end_frame=0000000115FFF1F0 target_ip=0000007FFF89B5BC
097c:trace:seh:RtlUnwindEx  info[0]=0000000000000040
097c:trace:seh:RtlUnwindEx  info[1]=000000000ff9e900
097c:trace:seh:RtlUnwindEx  pc=0000007fffa13e60  sp=0000000115ffd8d0  lr=0000000000000000  fp=0000007fffabc1a0
097c:trace:seh:RtlUnwindEx  x0=0000000000000000  x1=0000007fff89b5bc  x2=0000000115ffed70  x3=0000000115ffe5f8
097c:trace:seh:RtlUnwindEx  x4=0000000115ffde80  x5=0000000000000000  x6=0000000115fff1f0  x7=0000000115ffe9c0
097c:trace:seh:RtlUnwindEx  x8=0000000115fff1f0  x9=0000000060000000 x10=0000000115eff890 x11=0000000000000000
097c:trace:seh:RtlUnwindEx x12=0000000000000031 x13=000000000000009b x14=0000007fffb00000 x15=0000007fffab6330
097c:trace:seh:RtlUnwindEx x16=0000007fffa21b74 x17=0000007fffa199ec x18=000000000ece0000 x19=00000000c0000144
097c:trace:seh:RtlUnwindEx x20=0000000115ffde80 x21=0000000115ffe9c0 x22=0000000115ffed70 x23=0000000115fff1f0
097c:trace:seh:RtlUnwindEx x24=0000000000000000 x25=0000007fff89b5bc x26=0000000115ffe5f8 x27=0000007fffb00000
097c:trace:seh:RtlUnwindEx x28=0000007fffabc1e8 cpsr=40000000 fpcr=00000000 fpsr=00000000
097c:trace:seh:RtlUnwindEx calling handler 0000007FFF9E5CF4 (rec=0000000115FFED70, frame=115ffe240 context=0000000115FFDE80, dispatch=0000000115FFDC98)
097c:trace:seh:RtlUnwindEx handler 0000007FFF9E5CF4 returned 1
097c:trace:seh:RtlUnwindEx calling handler 0000007FFF89B5E0 (rec=0000000115FFED70, frame=115fff1f0 context=0000000115FFDE80, dispatch=0000000115FFDC98)
097c:trace:seh:RtlUnwindEx handler 0000007FFF89B5E0 returned 1
097c:trace:seh:RtlRestoreContext returning to 7fff89b5bc stack 115ffee30
097c:trace:seh:RtlGetExtendedContextLength2 context_flags 0x1003f, length 0000000115FFEB14, compaction_mask ffffffffffffffff.
097c:trace:seh:RtlInitializeExtendedContext2 context 000000000FF9E418, context_flags 0x1003f, context_ex 0000000115FFEB18, compaction_mask ffffffffffffffff.
097c:warn:seh:dispatch_exception "src\\common\\asyncfileiohandler.cpp (769) : dwRet != WAIT_FAILED\n"
097c:trace:seh:dispatch_exception code=40010006 (DBG_PRINTEXCEPTION_C) flags=0 addr=7A322339
097c:trace:seh:dispatch_exception  info[0]=00000040
097c:trace:seh:dispatch_exception  info[1]=0FF9E900
097c:trace:seh:dispatch_exception eip=7a322339 esp=0ff9e700 ebp=0ff9e754 eflags=00000246
097c:trace:seh:dispatch_exception eax=0ff9e700 ebx=00000002 ecx=00000008 edx=0ff9e898
097c:trace:seh:dispatch_exception esi=00000002 edi=0ff9e900 cs=0023 ds=002b es=002b fs=0053 gs=002b ss=002b
097c:trace:seh:call_vectored_handlers calling handler at 77B3DBE0 code=40010006 flags=0
097c:trace:seh:call_vectored_handlers handler at 77B3DBE0 returned 0
097c:trace:seh:call_seh_handlers calling handler at 7A755980 code=40010006 flags=0
097c:trace:seh:__regs_RtlUnwind code=40010006 flags=2
097c:trace:seh:__regs_RtlUnwind eip=7a755972 esp=0ff9e1ac ebp=0ff9e1b4 eflags=00000212
097c:trace:seh:__regs_RtlUnwind eax=00000000 ebx=0ff9e76c ecx=0ff9e3c8 edx=0ff9e76c
097c:trace:seh:__regs_RtlUnwind esi=00000001 edi=0ff9e3c8 cs=0023 ds=002b es=002b fs=0053 gs=002b ss=002b
097c:trace:seh:__regs_RtlUnwind calling handler at 7BE1AF50 code=40010006 flags=2
097c:trace:seh:__regs_RtlUnwind handler at 7BE1AF50 returned 1
03f8:trace:seh:dispatch_exception code=c0000005 (EXCEPTION_ACCESS_VIOLATION) flags=0 addr=0000007ED944B016
03f8:trace:seh:dispatch_exception  info[0]=0000000000000001
03f8:trace:seh:dispatch_exception  info[1]=0000007B203E3000
03f8:trace:seh:dispatch_exception rip=0000007ed944b016 rsp=0000007b07a4f448 rbp=0000007b203e2730 eflags=00000202
03f8:trace:seh:dispatch_exception rax=0000007b203e2730 rbx=0000006407a8c000 rcx=0000007b203e2f40 rdx=0000007b20500d80
03f8:trace:seh:dispatch_exception rsi=0000000000000c40 rdi=0000007b203e2731  r8=0000000000000430  r9=fffffffffffffff0
03f8:trace:seh:dispatch_exception r10=0000007ed58a0000 r11=0000000000000000 r12=0000007b20500571 r13=0000006408a67a58
03f8:trace:seh:dispatch_exception r14=0000000000000003 r15=0000007b20500570 mxcsr=00001fa5
03f8:trace:seh:call_vectored_handlers calling handler at 0000007ED648D3D0 code=c0000005 flags=0
03f8:trace:seh:call_vectored_handlers handler at 0000007ED648D3D0 returned 0
03f8:trace:seh:call_vectored_handlers calling handler at 0000007ED4D69A10 code=c0000005 flags=0
03f8:trace:seh:call_vectored_handlers handler at 0000007ED4D69A10 returned 0
03f8:trace:seh:call_seh_handlers calling handler 0000007FFFA3F47C (rec=0000007B07A4F390, frame=7b07a50000 context=0000007B07A4EB10, dispatch=0000007B07A4E748)
**wine: Unhandled page fault on write access to 0000007B203E3000 at address 0000007ED944B016 (thread 03f8), starting debugger...**
03f8:trace:seh:start_debugger Starting debugger L"winedbg --auto 864 756"
0154:trace:seh:RtlUnwindEx code=80000026 flags=2 end_frame=00000001001FEF00 target_ip=0000007FFF89C698
0154:trace:seh:RtlUnwindEx  info[0]=00000001001fede0
0154:trace:seh:RtlUnwindEx  pc=0000007fffa13e60  sp=00000001001fd840  lr=0000000000000000  fp=000000007ac77000
0154:trace:seh:RtlUnwindEx  x0=0000000000000000  x1=0000007fff89c698  x2=00000001001fe198  x3=0000000000000001
0154:trace:seh:RtlUnwindEx  x4=00000001001fddf0  x5=0000000000000000  x6=0000001000000003  x7=000000007a851cec
0154:trace:seh:RtlUnwindEx  x8=00000001001fef00  x9=0000000000000001 x10=00000001001ff148 x11=0000000000000000
0154:trace:seh:RtlUnwindEx x12=0000000000000000 x13=0000000074a0aa80 x14=000000000012ede8 x15=000000000012edfc
0154:trace:seh:RtlUnwindEx x16=0000007fff89c258 x17=0000000074a0aa40 x18=000000007ffc0000 x19=0000000100206910
0154:trace:seh:RtlUnwindEx x20=00000001001fddf0 x21=000000007ac76000 x22=00000001001fe198 x23=00000001001fef00
0154:trace:seh:RtlUnwindEx x24=000000007ffc2000 x25=0000007fff89c698 x26=0000000000200242 x27=000000007ac78002
0154:trace:seh:RtlUnwindEx x28=00000001001fe310 cpsr=60000000 fpcr=00000000 fpsr=00000010
0154:trace:seh:RtlUnwindEx calling handler 0000007FFF89B640 (rec=00000001001FE198, frame=1001fe260 context=00000001001FDDF0, dispatch=00000001001FDC08)
0154:trace:seh:RtlUnwindEx handler 0000007FFF89B640 returned 1
0154:trace:seh:RtlUnwindEx calling handler 0000007FFF89B690 (rec=00000001001FE198, frame=1001fe800 context=00000001001FDDF0, dispatch=00000001001FDC08)
0154:trace:seh:RtlUnwindEx handler 0000007FFF89B690 returned 1
0154:trace:seh:RtlRestoreContext returning to 7fff89c698 stack 1001fe800`

And i found there is lots of "src\\common\\asyncfileiohandler.cpp (769) : dwRet != WAIT_FAILED" exception throw, and catching backtrace via winedbg and winedbg will crash.

I don't know if it's wine issue or FEX issue.

You can reproduce this issue on Hangover, running steam with cef breakpad disable `"steam -cef-disable-breakpad -disable-winh264"`。after login and waiting a little bit, do something and it will be crashed.

It's working normal when using box64 + x86 wine.

**Comment by Art-Chen** [comment]
Update:
Updated FEX to master latest commit.


after disable some v8 flag, we can get the stable and low probability crash here:

```
0364:err:seh:dispatch_exception backtrace: --- Exception 0xc0000005.
0364:err:seh:virtual_unwind backtrace: 0000004FF1A52FB0: L"libcef.dll" + 00000000027C2FB0.
0364:err:seh:virtual_unwind backtrace: 0000004FF1A51799: L"libcef.dll" + 00000000027C1799.
0364:err:seh:virtual_unwind backtrace: 0000004FF1A513D8: L"libcef.dll" + 00000000027C13D8.
0364:err:seh:virtual_unwind backtrace: 0000004FF1A6AD7B: L"libcef.dll" + 00000000027DAD7B.
0364:err:seh:virtual_unwind backtrace: 0000004FF16E506B: L"libcef.dll" + 000000000245506B.
0364:err:seh:virtual_unwind backtrace: 0000004FF2BE246B: L"libcef.dll" + 000000000395246B.
0364:err:seh:virtual_unwind backtrace: 0000004FF2B7A300: L"libcef.dll" + 00000000038EA300.
0364:err:seh:virtual_unwind backtrace: 0000004FF2B02531: L"libcef.dll" + 0000000003872531.
0364:err:seh:virtual_unwind backtrace: 0000004FF0F2730E: L"libcef.dll" + 0000000001C9730E.
0364:err:seh:virtual_unwind backtrace: 0000004FF29A22E3: L"libcef.dll" + 00000000037122E3.
0364:err:seh:virtual_unwind backtrace: 0000004FF0F1F246: L"libcef.dll" + 0000000001C8F246.
0364:err:seh:virtual_unwind backtrace: 0000004FF29A504F: L"libcef.dll" + 000000000371504F.
0364:err:seh:virtual_unwind backtrace: 0000004FF0F1E0F5: L"libcef.dll" + 0000000001C8E0F5.
0364:err:seh:virtual_unwind backtrace: 0000004FF0F1DF1F: L"libcef.dll" + 0000000001C8DF1F.
```

I got this backtrace and found that `27C2FB0` pointed to x86_64 assembly `cvtsd2ss`, and the fault is 
`wine: Unhandled page fault on read access to 00000009030DF000 at address 0000004FF1A52FB0 (thread 0364), starting debugger...`

so it maybe the SSE float issue?

How can i print the actual arm64 assembly or any debug to check what is wrong?

Looks like @bylaws is the Pro on ARM64EC and Wine side, What's your opinion here?

**Comment by Art-Chen** [comment]
cef download link: [download](https://cdn.steamstatic.com/client/bins_webhelpers_win32_win7-64.zip.d886cb7b596c1b2c23f3268f716bbef65fb286a1)

**Comment by bylaws** [comment]
Oooh I'll look, what flags are you running with?

**Comment by Art-Chen** [comment]
> Oooh I'll look, what flags are you running with?

`--js-flags='--no-maglev,--lite-mode,--no-compact'`

The CEF 126 crashed randomly when doing gc + page compact(died on `memmove`), and sometimes died on maglev that also doing `memmove`, so i made a workaround is just disable them. looks fine now.

**Comment by bylaws** [comment]
the link you sent doesn't have libcef afaict

**Comment by Art-Chen** [comment]
> the link you sent doesn't have libcef afaict
> 

sry, it should be this link:
https://cdn.steamstatic.com/client/bins_cef_win32_win7-64.zip.e181b76c5620a86fc85fd5e9995022eb3a2c053b


md5sum libcef.dll                                 ce8bf80702f29a9828226f181e90033e  libcef.dll

**Comment by bylaws** [comment]
Fixed the gc issue... spent far too long reading the gc source code before enabling +virtual logs and seeing it was something obvious

**Comment by Art-Chen** [comment]
> Fixed the gc issue... spent far too long reading the gc source code before enabling +virtual logs and seeing it was something obvious

Wow! You are freaking awesome!

so it looks like also fixed this? i'm not sure this trace is related to gc. but it's memory issue too, i'll check if it's fixed.

and my js-flags will be removed since unneeded.

> 0364:err:seh:dispatch_exception backtrace: --- Exception 0xc0000005.
> 0364:err:seh:virtual_unwind backtrace: 0000004FF1A52FB0: L"libcef.dll" + 00000000027C2FB0.
> 0364:err:seh:virtual_unwind backtrace: 0000004FF1A51799: L"libcef.dll" + 00000000027C1799.
> 0364:err:seh:virtual_unwind backtrace: 0000004FF1A513D8: L"libcef.dll" + 00000000027C13D8.
> 0364:err:seh:virtual_unwind backtrace: 0000004FF1A6AD7B: L"libcef.dll" + 00000000027DAD7B.

**Comment by bylaws** [comment]
I kept steam open for 5 mins and downloaded and played a game and saw no crash. I made a simple unit test and the instruction isn't doing anything obviously wrong, so I think things are fine? Thought that might be the same core issue.

Lmk if you can still reproduce it and if so how and your CPU details. Then grab a full log with +seh,+unwind

**Comment by Art-Chen** [comment]
> I kept steam open for 5 mins and downloaded and played a game and saw no crash. I made a simple unit test and the instruction isn't doing anything obviously wrong, so I think things are fine? Thought that might be the same core issue.
> 
> Lmk if you can still reproduce it and if so how and your CPU details. Then grab a full log with +seh,+unwind

Unfortunately, the crash still reproduced.

reproduce step:
Open Steam with gamepad ui -> randomly switch page(click library game, back, go to settings, back, and just do all random)

sometimes it can reproduce, most time works well.

Log:

[crash.log](https://github.com/user-attachments/files/21649101/crash.log)

The 27A85E4 is also the `cvtsd2ss`

**Comment by bylaws** [comment]
fixed this, silly bug

**Comment by Art-Chen** [comment]
> fixed this, silly bug

Wow! You are so fucking awesome!
